# fly.toml app configuration file generated for task-manager-api-red-dust-7398 on 2025-09-30T19:51:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'task-manager-api-red-dust-7398'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DJANGO_SETTINGS_MODULE = 'taskmanager.settings'
  FLY_APP_NAME = 'task-manager-api-red-dust-7398'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "bash -lc 'python manage.py migrate --noinput && python manage.py collectstatic --noinput'"

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
